import "./globals.css";
import Header from "./components/header.jsx";

export const metadata = {
  title: "Saratoga-Springs Hub",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
      </body>
    </html>
  );
}
