import { Google_Sans_Code } from "next/font/google";
import "./globals.css";
import Header from "./components/header.jsx";

const googleSans = Google_Sans_Code({
  variable: "--font-google-sans-code",
  subsets: ["latin"],
});


export const metadata = {
  title: "Saratoga-Springs Hub",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${googleSans.variable} antialiased`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
